CREATE TABLE [dbo].[TB_LISTA_ADD](
	[ID_LISTA] INT IDENTITY NOT NULL,
	[ID_PEDIDO] INT NOT NULL,
	[ID_ADD] INT NULL,
	[QTD] INT NULL,
	[VALOR] DECIMAL(6,2) NOT NULL,
	CONSTRAINT [PK_LISTA_ADICIONAL] PRIMARY KEY ([ID_LISTA]),
	CONSTRAINT [FK_PEDIDO_ADD] FOREIGN KEY ([ID_PEDIDO]) REFERENCES [TB_PEDIDO]([ID_PEDIDO]),
	CONSTRAINT [FK_ADICIONAL] FOREIGN KEY ([ID_ADD]) REFERENCES [TB_ADICIONAIS]([ID_ADD])
)
GO