CREATE TABLE [dbo].[TB_LISTA_PASTEL](
	[ID_LISTA] INT IDENTITY NOT NULL,
	[ID_PEDIDO] INT NOT NULL,
	[ID_PASTEL] INT NULL,
	[QTD] INT NULL,
	[VALOR] DECIMAL(6,2) NOT NULL,
	CONSTRAINT [PK_LISTA_PASTEL] PRIMARY KEY ([ID_LISTA]),
	CONSTRAINT [FK_PEDIDO_PASTEL] FOREIGN KEY ([ID_PEDIDO]) REFERENCES [TB_PEDIDO]([ID_PEDIDO]),
	CONSTRAINT [FK_PASTEL] FOREIGN KEY ([ID_PASTEL]) REFERENCES [TB_PASTEL]([ID_PASTEL])
)
GO