CREATE TABLE  [dbo].[TB_LOGIN](
	[ID_LOG] INT IDENTITY NOT NULL,
	[EMAIL] VARCHAR(100) NOT NULL,
	[NICK] VARCHAR(50) NOT NULL,
	[SENHA] VARCHAR(32) NOT NULL,
	[PERFIL] INT NOT NULL,
	[STATUS] INT NOT NULL,
	CONSTRAINT [PK_LOGIN] PRIMARY KEY ([ID_LOG])
)
GO