CREATE TABLE [dbo].[TB_PASTEL](
	[ID_PASTEL] INT IDENTITY NOT NULL,
	[DESC] VARCHAR(50) NOT NULL,
	[VALOR] DECIMAL(6,2) NOT NULL,
	[STATUS] INT NOT NULL,
	CONSTRAINT [PK_PASTEL] PRIMARY KEY([ID_PASTEL])
)
GO