CREATE TABLE [dbo].[TB_PEDIDO](
	[ID_PEDIDO] INT IDENTITY NOT NULL,
	[DATA] DATE NOT NULL,
	[HORA] TIME NOT NULL,
	[ID_CLIENTE] INT NOT NULL,
	[ID_PGTO] INT NOT NULL,
	CONSTRAINT [PK_PEDIDO] PRIMARY KEY([ID_PEDIDO]),
	CONSTRAINT [FK_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [TB_CLIENTE]([ID_CLIENTE]),
	CONSTRAINT [FK_PAGAMENTO] FOREIGN KEY ([ID_PGTO]) REFERENCES [TB_PGTO]([ID_PGTO])
)
GO